---
title: "Container calculation"
author: "LonghaoChen"
date: "10/27/2019"
output: pdf_document
---

This is a mini project designed to calculate the quantity of goods to fit in containers. The algorithms are designed to fill to the containers 90% capacity as close as possible.

```{r setup, include=FALSE}
library(tidyverse)
library(readxl)
library(msm)
```

First we need to generate some data
```{r}
df <- data.frame()
# We need Id to identify different products
df[1:50, "id"] <- as.vector(paste("A-", seq(1:50), sep = ""))
# For each Id there is corresponding QTY/Pallet
df[1:50, "QTY/Pallet"] <- abs(round(rnorm(n = 50, mean = 10, sd = 2)))
# Desired quantity
df[1:50, "quantity"] <- abs(round(rnorm(n = 50, mean = 50, sd = 5)))
# Each product has is volume
df[1:50, "volume"] <- abs(runif(n = 50, min = 0.01, max = 1))
```



```{r}
# Define some parameters
container_space <- 32.6 # The unit is in m^3
space_ratio <- 0.9 # We would like to fill up to 90 percent of container space
n <- 1000 # Number of simulation
sd <- 0.5 # Standard deviation
min_pallet <- 1 # minimum of 1 pallet
best_n <- 10 # Select the best 10 combinations
  

set.seed(1)

best_combination <- function(container_space=32.6, space_ratio=0.9, n=1000, sd=0.5, min_pallet=1,best_n = 10) {
  # Find the minimum number of pallets
  df$pallet <- ceiling(df$quantity / df$`QTY/Pallet`)
  #Generate random number around desired quantity of pallet
  set <- data.frame()
  for (i in 1:dim(df)[1]) {
    set[1:n, i] <- round(rtnorm(1:n, mean = as.numeric(df[i, "pallet"]), sd = sd, lower = min_pallet))
  }
  colnames(set)[] <- df$id
  #Calculate total product quantity from pallet
  random <- t(t(set) * df[["QTY/Pallet"]])
  #Calculate total volume
  volume <- as.matrix(random) %*% as.matrix(df[, "volume"])
  combination <- as.data.frame(volume / container_space * space_ratio)
  combination$round <- round(combination$V1)
  #Find out the difference between calculated volume and so-called perfect containers quantities
  combination$difference <- abs(combination$V1 - combination$round)
  random <- cbind(as.data.frame(random), difference = combination[, "difference"], n_containers = combination[, "round"])
  #Return the list of best
  best <<- head(arrange(random, difference), n = best_n)

}

best_combination(container_space = 40, space_ratio = 0.85, n = 2000, sd = 1, min_pallet = 1,best_n=30)
```


